# Generated by Django 6.0.3 on 2026-03-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_created_at_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(help_text='eduction', max_length=100),
        ),
    ]
